# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UtilsSamples' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UtilsSamples
  pod "nKit.iOS", :git => "https://github.com/vbenkevich/ios_swift_utils.git", branch: "develop"
end
